# [_____ Font _____]
font_family FiraCode Nerd Font
font_size 16

# [_____ Audio _____]
enable_audio_bell no

# [_____ Window _____]
hide_window_decorations yes

# [_____ Cursor _____]
cursor_shape block
shell_integration no-cursor

# [______ Theme & background ______]
# include ./themes/dracula.conf

background #333333
background_opacity 0.85
# background_tint 0.88

# background_image /home/joe/.config/kitty/resources/core-1920x1080.png
# background_image /home/joe/.config/kitty/resources/macbook-sequoia/yellow.png

# background_image_layout scaled